server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  max_header_bytes: 1048576  # 1MB
  shutdown_timeout: "10s"
  enable_cors: true
  enable_swagger: true
  permissions_disabled: true  # 开发环境禁用权限检查

database:
  host: "localhost"
  port: 5432
  user: "luckdb"
  password: "luckdb"
  name: "luckdb_dev"
  ssl_mode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "1h"
  log_level: "info"  # 显示所有SQL查询

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  dial_timeout: "5s"

jwt:
  secret: "your-secret-key-change-in-production"
  access_token_ttl: "24h"
  refresh_token_ttl: "168h"  # 7 days
  issuer: "teable-api"
  enable_refresh: true

storage:
  type: "local"
  local:
    upload_path: "./uploads"
    url_prefix: "/uploads"
  cdn_domain: ""

logger:
  level: "info"
  format: "json"
  output_path: "stdout"

# SQL日志配置 - 单独记录到文件，纯文本格式方便复制
sql_logger:
  enabled: true
  output_path: "logs/sql.log"  # SQL日志文件路径
  max_size: 100                 # 单个文件最大大小(MB)
  max_backups: 5               # 保留的旧日志文件数量
  max_age: 30                  # 保留的最大天数
  compress: false              # 不压缩，方便查看

queue:
  redis_addr: "localhost:6379"
  redis_password: ""
  redis_db: 1
  max_retries: 3
  queue_critical: "critical"
  queue_default: "default"
  queue_low: "low"

websocket:
  enable_redis_pubsub: true
  redis_prefix: "teable:ws"
  heartbeat_interval: "30s"
  connection_timeout: "60s"
  max_connections: 1000
  enable_presence: true

# AI配置
ai:
  default_provider: openai
  providers:
    openai:
      type: openai
      api_key: ${OPENAI_API_KEY}  # 从环境变量获取
      default_model: gpt-3.5-turbo
      timeout: 30
      rate_limit:
        requests_per_minute: 60
        tokens_per_minute: 90000
        concurrent_requests: 10
    deepseek:
      type: deepseek
      api_key: ${DEEPSEEK_API_KEY}  # 从环境变量获取
      base_url: https://api.deepseek.com/v1
      default_model: deepseek-chat
      timeout: 30
      rate_limit:
        requests_per_minute: 60
        tokens_per_minute: 90000
        concurrent_requests: 10

# MCP配置
mcp:
  default_user_id: "usr_nw1aMrAIFMMLWy2HUH98o"  # 默认用户ID，用于MCP工具调用
  auto_migrate_on_start: true   # 启动时自动执行迁移脚本
  seed_on_empty: true           # 空库时自动种子数据
  seed:
    space_name: "Content Space"
    space_description: "用于内容管理的空间"
    base_name: "cms"
    base_description: "内容管理数据库"
    table_name: "blog_posts"
    table_description: "博客文章"
